services:
  svt-hhb3-2.10.2:
    image: custler/${CONTAINER_NAME}:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - USER_NAME=${USER_NAME}
        - HHB_VERSION=${HHB_VERSION}
    container_name: "${CONTAINER_NAME}"
    hostname: "${CONTAINER_NAME}"
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./data:/data
    working_dir: /data
    environment:
      - ZSTD_LIB_DIR=/usr/lib/x86_64-linux-gnu
      - TOOLROOT=/opt/riscv
    tty: true
    stdin_open: true

    networks:
      - private_net

###############################################################################
# Networks                                                                    #
###############################################################################
networks:
  # Private, internal-only bridge network isolated from other Compose stacks
  private_net:
    name: "${CONTAINER_NAME:-hhb3}_net"  # Unique, readable name
    driver: bridge
#    internal: true        # Block traffic to/from outside of this network
