services:
  svt-hhb3:
    image: custler/svt-hhb3:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - USER_NAME=${USER_NAME}
        - HHB_VERSION=${HHB_VERSION}
    container_name: svt-hhb3
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./data:/data
    working_dir: /data
    environment:
      - ZSTD_LIB_DIR=/usr/lib/x86_64-linux-gnu
      - TOOLROOT=/opt/riscv
      - RISCV_CFLAGS=-march=rv64gcv_zfh_xtheadc -mabi=lp64d -O3
    tty: true
    stdin_open: true
